### ISSUE TITLE
Changing license

### ISSUE THREAD

**Issue by sheriferson** [sheriferson/simplestatistics#4]
@tmcw I've been working on the package and am preparing to put it up on PyPI. Do you still want to keep the license as Copyright Tom MacWright, or do I have your permission to change it to something else?
(not sure how this copyright change stuff works or if there are protocols for it).

**Comment by tmcw** [comment]
Just requires signoff by the authors. You've got my signoff, do whatever you want with the license!

**Comment by sheriferson** [comment]
Thank you!
